# Generated by Django 3.2.12 on 2022-05-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_auth',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('auth_number', models.IntegerField(default=0)),
                ('is_auth', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sms_auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.sms_auth'),
            preserve_default=False,
        ),
    ]
