# Generated by Django 3.2.12 on 2022-05-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='base_prpfile_img.jpeg', upload_to='images/'),
        ),
    ]
