# Generated by Django 3.2.12 on 2022-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220522_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sms_auth',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
